baseURL = "https://Nabi.github.io/Nabi-blog/"
languageCode = 'en-us'
title = "Nabi's Portfolio"
theme = "hermit-v2"
[params]
  author = "Nabi"
  description = "A portfolio about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/lochanora"

  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/zilu-he-5282a123b/"
